# create a user in IAM with full access to EC2
# set AWS_ACCESS_KEY_ID, AWS_SECRET_ACCESS_KEY env variables
# create key pair in EC2 section
# create subnet in the region
# get the image number from launch ec2 section
#  [localhost]
#  localhost ansible_connection=local ansible_python_interpreter=python
# ssh-add mykey.pem
- hosts: localhost
  tasks:
#    - ec2:
#          key_name: mykey
#          instance_type: t2.medium
#          image: ami-00399ec92321828f5
#          wait: yes
#          group: default # security group
#          count: 1
#          vpc_subnet_id: subnet-097e6f9cbffc5754c
#          region: us-east-2
#          assign_public_ip: yes
#          instance_tags:
#              type: jenkins
#      name: jenkins
    - ec2:
          key_name: mykey
          instance_type: t2.medium
          image: ami-00399ec92321828f5
          wait: yes
          group: default # security group
          count: 2
          vpc_subnet_id: subnet-097e6f9cbffc5754c
          region: us-east-2
          assign_public_ip: yes
          instance_tags:
              type: kubernetes
      name: kubernetes