# ssh-agent bash
# ssh-add mykey.pem
- hosts: jenkins
  become: true
  remote_user: ubuntu
  tasks:
    - name: apt update
      apt:
        update-cache: true
    - name: add key
      apt_key:
        url: "{{ item }}"
        state: present
      loop:
        - https://download.docker.com/linux/ubuntu/gpg
        - https://pkg.jenkins.io/debian-stable/jenkins.io.key

    - name: add repositories
      apt_repository:
        repo: deb http://pkg.jenkins.io/debian-stable binary/
        state: present
#        filename: 'jenkins'
      loop:
        - "deb http://pkg.jenkins.io/debian-stable binary/"
        - "ppa:ansible/ansible"
        - "deb https://download.docker.com/linux/ubuntu bionic stable"
    - name: install packages
      apt:
        name: "{{ item }}"
        state: present
        update_cache: yes
      loop:
        - openjdk-11-jdk
        - apt-transport-https
        - ca-certificates
        - curl
        - gnupg-agent
        - software-properties-common
        - jenkins
        - docker.io

    - name: start and enable services
      service:
        name: "{{ item }}"
        state: started
        enabled: yes
      loop:
        - jenkins
        - docker

    - name: add jenkins user to docker group
      user:
        name: jenkins
        groups: docker
        append: yes
