- hosts: localhost
  become: yes
  tasks:
    - name: update
      apt:
        update_cache: yes
    - name: install transport
      apt:
        name: apt-transport-https
        state: present
    - name: add key
      apt_key:
        url: "https://packages.cloud.google.com/apt/doc/apt-key.gpg"
        state: present
    - name: add repository
      apt_repository:
        repo: deb http://apt.kubernetes.io/ kubernetes-xenial main
        state: present
    - name: install containerd kubectl
      apt:
        name: "{{ item }}"
        state: present
      loop:
        - kubelet
        - kubeadm
        - kubectl
        - docker.io
    - name: start docker
      service:
        name: docker
        state: started
        enabled: yes

    - name: run shell commands
      shell: "modprobe {{ item }}"
      loop:
        - overlay
        - br_netfilter
    - name: update kernel parameters
      copy:
        dest: /etc/sysctl.d/99-kubernetes-cri.conf
        content: |
          net.bridge.bridge-nf-call-iptables = 1
          net.bridge.bridge-nf-call-ip6tables = 1
          net.ipv4.ip_forward = 1
    - name: disable swap
      shell: swapoff -a